from __future__ import annotations

from copy import deepcopy
from typing import Any


def _telemetry(
    vibration: float,
    kurtosis: float,
    crest: float,
    temperature: float,
    speed: float,
    load: float,
    acoustic: float,
    current: float,
    energy: float,
    quality: float = 0.97,
) -> dict[str, float]:
    return {
        "vibration_rms_g": vibration,
        "vibration_kurtosis": kurtosis,
        "crest_factor": crest,
        "temperature_c": temperature,
        "rotational_speed_rpm": speed,
        "load_percent": load,
        "acoustic_rms_db": acoustic,
        "current_rms_a": current,
        "energy_kw": energy,
        "quality": quality,
    }


def _maintenance(
    title: str,
    description: str,
    parts: list[str],
    skills: list[str],
    downtime: int,
    cost: float,
    team: str,
    constrained_title: str = "降载运行至最近安全窗口",
    constrained_description: str = "降低负载、提高采样频率，并在硬停机阈值触发前转入维修。",
) -> dict[str, Any]:
    return {
        "title": title,
        "description": description,
        "parts": parts,
        "skills": skills,
        "downtime": downtime,
        "cost": cost,
        "team": team,
        "constrained_title": constrained_title,
        "constrained_description": constrained_description,
    }


SCENARIOS: list[dict[str, Any]] = [
    {
        "id": "outer_race_spall",
        "name": "轴承外圈剥落",
        "category": "轴承与旋转机械",
        "description": "周期性冲击、高峭度与局部表面缺陷共同指向外圈局部剥落。",
        "modalities": ["振动", "视觉", "温度"],
        "severity": "high",
        "asset_types": ["轴承", "主轴", "电机"],
        "summary": "2号线主轴轴承出现周期性冲击，表面存在可见缺陷。",
        "telemetry": _telemetry(3.18, 7.84, 5.42, 78.6, 2980, 83, 76.2, 4.8, 14.2),
        "vision": {"anomaly_score": 0.91, "class_name": "outer_race_spall", "confidence": 0.88},
        "operator_note": "负载运行时出现间歇性金属异响。",
        "fault_mode": "outer-race localized spalling",
        "rationale": "高峭度与高峰值因子表明重复冲击，视觉局部缺陷提供了独立证据。",
        "alternatives": ["轴承内圈局部缺陷", "传感器安装松动"],
        "maintenance": _maintenance("受控停机并更换轴承", "在最近安全生产窗口停机隔离，更换轴承并完成对中、润滑和复测。", ["6205-2RS-C3 bearing", "approved grease cartridge", "locking washer"], ["mechanical maintenance", "LOTO authorization", "vibration verification"], 55, 460, "机械可靠性 A 组"),
    },
    {
        "id": "inner_race_defect",
        "name": "轴承内圈故障",
        "category": "轴承与旋转机械",
        "description": "转速同步调制冲击与包络谱侧带提示内圈局部损伤。",
        "modalities": ["振动", "转速"],
        "severity": "high",
        "asset_types": ["轴承", "主轴"],
        "summary": "主轴转速同步冲击增强，内圈故障特征频率及侧带明显。",
        "telemetry": _telemetry(2.92, 7.31, 5.18, 72.4, 3010, 79, 72.5, 4.7, 13.7),
        "vision": {"anomaly_score": 0.33, "class_name": None, "confidence": 0.46},
        "operator_note": "高转速阶段振动周期随轴速变化。",
        "fault_mode": "轴承内圈局部缺陷",
        "rationale": "冲击呈转速同步调制且温升有限，更符合随轴旋转的内圈损伤。",
        "alternatives": ["外圈局部剥落", "转子不平衡"],
        "maintenance": _maintenance("受控停机检查并更换轴承", "拆检内圈滚道与配合面，更换轴承并验证安装游隙。", ["6205-2RS-C3 bearing", "locking washer"], ["mechanical maintenance", "bearing inspection", "LOTO authorization"], 60, 490, "机械可靠性 A 组"),
    },
    {
        "id": "rolling_element_defect",
        "name": "滚动体故障",
        "category": "轴承与旋转机械",
        "description": "非稳定冲击与包络调制提示滚珠或滚子表面损伤。",
        "modalities": ["振动", "声学"],
        "severity": "high",
        "asset_types": ["轴承"],
        "summary": "滚动体通过载荷区时产生不稳定冲击，声学噪声同步升高。",
        "telemetry": _telemetry(2.78, 6.94, 5.01, 70.8, 2950, 82, 79.2, 4.6, 13.5),
        "vision": {"anomaly_score": 0.48, "class_name": "rolling_element_pit", "confidence": 0.66},
        "operator_note": "设备低速盘车时可听到不规则咔嗒声。",
        "fault_mode": "滚动体表面损伤",
        "rationale": "不规则冲击和声学峰值与滚动体缺陷进入载荷区的行为一致。",
        "alternatives": ["保持架松动", "润滑污染"],
        "maintenance": _maintenance("更换轴承并检查污染来源", "更换轴承，检查密封、润滑脂污染和装配清洁度。", ["6205-2RS-C3 bearing", "approved grease cartridge", "seal kit"], ["mechanical maintenance", "contamination inspection", "LOTO authorization"], 65, 540, "机械可靠性 A 组"),
    },
    {
        "id": "lubrication_failure",
        "name": "润滑失效",
        "category": "轴承与旋转机械",
        "description": "温升、宽频振动与摩擦声增强，但没有明确局部剥落证据。",
        "modalities": ["温度", "振动", "声学"],
        "severity": "high",
        "asset_types": ["轴承", "齿轮箱"],
        "summary": "换班后轴承温度与宽频振动持续上升。",
        "telemetry": _telemetry(2.42, 4.8, 3.9, 91.3, 3010, 88, 71.4, 5.1, 15.1),
        "vision": {"anomaly_score": 0.39, "class_name": None, "confidence": 0.36},
        "operator_note": "润滑脂储罐两周前补充过。",
        "fault_mode": "润滑退化或异常摩擦",
        "rationale": "显著温升伴随宽频振动而无局部视觉损伤，优先指向润滑或摩擦问题。",
        "alternatives": ["轴承预紧过大", "冷却不足"],
        "maintenance": _maintenance("停机检查并恢复润滑系统", "核对润滑剂型号和用量，清理旧脂，检查油路并执行复润滑。", ["approved grease cartridge", "lubrication sampling kit"], ["lubrication maintenance", "thermography", "LOTO authorization"], 35, 180, "润滑与机械可靠性组"),
    },
    {
        "id": "shaft_misalignment",
        "name": "轴系不对中",
        "category": "轴承与旋转机械",
        "description": "轴向振动、二倍频与联轴器温升共同提示角向或平行不对中。",
        "modalities": ["振动", "温度", "激光对中"],
        "severity": "medium",
        "asset_types": ["电机", "泵", "联轴器"],
        "summary": "联轴器两侧轴向振动和二倍频分量升高，联轴器温度增加。",
        "telemetry": _telemetry(2.21, 4.2, 3.7, 74.5, 1800, 76, 69.4, 5.0, 14.1),
        "vision": {"anomaly_score": 0.45, "class_name": "coupling_offset", "confidence": 0.71},
        "operator_note": "设备上周更换过底座垫片。",
        "fault_mode": "轴系角向或平行不对中",
        "rationale": "轴向振动与二倍频增大，并伴随联轴器热异常，符合不对中模式。",
        "alternatives": ["软脚", "轴弯曲"],
        "maintenance": _maintenance("停机执行激光对中", "检查软脚、底座与热膨胀补偿，使用激光对中仪校正轴系。", ["laser alignment kit", "shim set"], ["precision alignment", "mechanical maintenance", "LOTO authorization"], 70, 720, "机械可靠性 A 组"),
    },
    {
        "id": "rotor_imbalance",
        "name": "转子不平衡",
        "category": "轴承与旋转机械",
        "description": "径向一倍频主导且相位稳定，提示质量偏心或积灰。",
        "modalities": ["振动", "相位", "转速"],
        "severity": "medium",
        "asset_types": ["风机", "转子", "电机"],
        "summary": "径向一倍频振动显著增大，相位稳定且随转速平方增长。",
        "telemetry": _telemetry(2.36, 3.4, 3.1, 66.2, 1480, 74, 67.3, 4.4, 12.9),
        "vision": {"anomaly_score": 0.58, "class_name": "rotor_deposit", "confidence": 0.73},
        "operator_note": "叶轮清洗周期已超过计划两周。",
        "fault_mode": "转子质量不平衡",
        "rationale": "稳定一倍频径向振动与转速相关性符合质量偏心或积灰不平衡。",
        "alternatives": ["基础松动", "轴弯曲"],
        "maintenance": _maintenance("清洁转子并进行现场动平衡", "检查积灰、叶片损伤与配重，完成低速和工作转速复测。", ["balancing weight kit", "cleaning consumables"], ["field balancing", "vibration analysis", "LOTO authorization"], 80, 860, "旋转设备可靠性组"),
    },
    {
        "id": "mechanical_looseness",
        "name": "机械松动",
        "category": "轴承与旋转机械",
        "description": "多次谐波、冲击和底座位移提示紧固件或结构松动。",
        "modalities": ["振动", "视觉", "扭矩"],
        "severity": "high",
        "asset_types": ["电机", "泵", "风机"],
        "summary": "设备出现多次谐波和间歇冲击，底座连接处可见微动。",
        "telemetry": _telemetry(3.05, 6.2, 5.0, 69.5, 1770, 72, 75.1, 4.8, 13.8),
        "vision": {"anomaly_score": 0.79, "class_name": "base_looseness", "confidence": 0.84},
        "operator_note": "最近一次检修后未复核地脚螺栓扭矩。",
        "fault_mode": "机械连接或基础松动",
        "rationale": "多次谐波、冲击和可见微动共同支持结构松动。",
        "alternatives": ["不对中", "结构共振"],
        "maintenance": _maintenance("停机复核紧固与基础状态", "执行地脚和轴承座扭矩复核，检查裂纹、垫片和灌浆层。", ["torque tool", "fastener set", "shim set"], ["mechanical inspection", "torque verification", "LOTO authorization"], 45, 320, "机械可靠性 A 组"),
    },
    {
        "id": "shaft_bend",
        "name": "轴弯曲",
        "category": "轴承与旋转机械",
        "description": "一倍频径向与轴向分量并存，慢转测量显示轴径跳动。",
        "modalities": ["振动", "位移", "转速"],
        "severity": "high",
        "asset_types": ["主轴", "泵", "电机"],
        "summary": "轴向和径向一倍频同时升高，慢转跳动超过工艺允许值。",
        "telemetry": _telemetry(2.86, 4.7, 4.0, 73.1, 1450, 69, 70.8, 4.9, 13.9),
        "vision": {"anomaly_score": 0.51, "class_name": "shaft_runout", "confidence": 0.69},
        "operator_note": "设备曾发生短时卡滞。",
        "fault_mode": "轴弯曲或永久径向跳动",
        "rationale": "轴向与径向同步一倍频加上慢转跳动，支持轴弯曲判断。",
        "alternatives": ["不对中", "热弯曲"],
        "maintenance": _maintenance("停机测量轴跳动并修复或更换", "拆检轴系，进行百分表和激光测量，按允许值校直或更换。", ["dial indicator kit", "replacement shaft"], ["shaft inspection", "precision alignment", "LOTO authorization"], 180, 2800, "机械可靠性与机修组"),
    },
    {
        "id": "structural_resonance",
        "name": "结构共振",
        "category": "轴承与旋转机械",
        "description": "特定转速区间振幅急剧放大，避开该转速后迅速下降。",
        "modalities": ["振动", "转速扫频"],
        "severity": "medium",
        "asset_types": ["风机", "泵", "结构"],
        "summary": "设备在特定转速区间振幅急剧放大，离开该区间后快速恢复。",
        "telemetry": _telemetry(3.42, 3.9, 3.3, 64.7, 1620, 63, 73.0, 4.2, 12.8),
        "vision": {"anomaly_score": 0.27, "class_name": None, "confidence": 0.55},
        "operator_note": "变频器频率调整后异常出现。",
        "fault_mode": "结构或部件共振",
        "rationale": "窄转速区间的高幅响应是典型共振特征。",
        "alternatives": ["不平衡", "基础刚度下降"],
        "maintenance": _maintenance("开展模态确认并调整结构刚度", "设置临时禁用转速带，检查支撑并通过加固、阻尼或转速策略避开共振。", ["structural brace kit", "damping material"], ["modal testing", "structural maintenance", "controls engineering"], 120, 1900, "结构与旋转设备组"),
    },
    {
        "id": "gear_tooth_damage",
        "name": "齿轮齿面损伤",
        "category": "齿轮箱与传动",
        "description": "啮合频率边带、冲击和油液磨粒共同提示齿面点蚀或断齿。",
        "modalities": ["振动", "油液", "声学"],
        "severity": "high",
        "asset_types": ["齿轮箱", "减速机"],
        "summary": "齿轮啮合频率边带增强并出现周期冲击，油液磨粒计数升高。",
        "telemetry": _telemetry(3.12, 6.8, 5.3, 76.0, 960, 81, 78.1, 6.8, 17.2),
        "vision": {"anomaly_score": 0.76, "class_name": "gear_pitting", "confidence": 0.81},
        "operator_note": "减速机低负载时仍有周期异响。",
        "fault_mode": "齿轮齿面点蚀或局部损伤",
        "rationale": "啮合频率边带与周期冲击结合磨粒证据，支持齿面损伤。",
        "alternatives": ["齿轮偏心", "轴承故障"],
        "maintenance": _maintenance("停机内窥检查齿轮并制定修复", "检查齿面、侧隙和润滑油；根据损伤程度修磨或更换齿轮副。", ["gear inspection kit", "gear oil", "replacement gear set"], ["gearbox maintenance", "borescope inspection", "LOTO authorization"], 240, 5200, "传动系统可靠性组"),
    },
    {
        "id": "belt_slip",
        "name": "皮带打滑",
        "category": "齿轮箱与传动",
        "description": "转速比偏差、皮带温升和粉尘迹象提示张紧不足或打滑。",
        "modalities": ["转速", "温度", "视觉"],
        "severity": "medium",
        "asset_types": ["皮带传动", "风机"],
        "summary": "主动与从动端转速比偏离基线，皮带温升并出现磨屑。",
        "telemetry": _telemetry(1.86, 3.5, 3.1, 79.2, 1450, 72, 70.2, 4.5, 14.8),
        "vision": {"anomaly_score": 0.82, "class_name": "belt_slip", "confidence": 0.87},
        "operator_note": "雨季环境湿度升高后开始出现异味。",
        "fault_mode": "皮带打滑或张紧不足",
        "rationale": "转速比偏差和皮带热异常与磨屑证据共同指向打滑。",
        "alternatives": ["带轮不对中", "负载突增"],
        "maintenance": _maintenance("停机调整张紧并检查皮带", "检查张紧力、带轮对中与表面磨损，必要时更换皮带组。", ["matched belt set", "tension gauge"], ["belt maintenance", "precision alignment", "LOTO authorization"], 50, 380, "机械可靠性 A 组"),
    },
    {
        "id": "pump_cavitation",
        "name": "泵汽蚀",
        "category": "泵风机与流体设备",
        "description": "高频宽带噪声、吸入口压力不足和流量波动提示汽蚀。",
        "modalities": ["振动", "声学", "压力", "流量"],
        "severity": "high",
        "asset_types": ["离心泵"],
        "summary": "泵体高频宽带振动增强，吸入口压力偏低且流量波动。",
        "telemetry": _telemetry(2.73, 5.6, 4.4, 71.8, 2900, 84, 82.4, 7.2, 18.5),
        "vision": {"anomaly_score": 0.41, "class_name": "flow_instability", "confidence": 0.63},
        "operator_note": "储液罐液位近期低于常用区间。",
        "fault_mode": "离心泵汽蚀",
        "rationale": "高频宽带噪声与低吸入口压力、流量波动是汽蚀组合证据。",
        "alternatives": ["叶轮损伤", "管路进气"],
        "maintenance": _maintenance("降低负载并消除吸入侧限制", "检查液位、滤网、阀门、吸入管路和净正吸入压头，恢复后复测。", ["suction filter", "gasket kit"], ["pump maintenance", "process operations", "LOTO authorization"], 70, 680, "泵与公用工程组"),
    },
    {
        "id": "seal_leak",
        "name": "机械密封泄漏",
        "category": "泵风机与流体设备",
        "description": "泄漏视觉、压力下降和环境传感器共同提示密封失效。",
        "modalities": ["视觉", "压力", "环境"],
        "severity": "critical",
        "asset_types": ["泵", "搅拌器"],
        "summary": "泵机械密封区域检测到持续液滴，系统压力缓慢下降。",
        "telemetry": _telemetry(1.62, 3.6, 3.0, 69.4, 2850, 70, 67.5, 6.8, 16.2),
        "vision": {"anomaly_score": 0.94, "class_name": "seal_leak", "confidence": 0.93},
        "operator_note": "泄漏介质需要按 EHS 流程处置。",
        "fault_mode": "机械密封泄漏",
        "rationale": "持续泄漏视觉证据与压力下降形成直接因果证据。",
        "alternatives": ["法兰垫片泄漏", "冲洗系统异常"],
        "maintenance": _maintenance("立即隔离并更换机械密封", "按介质风险执行隔离、收集和清洗，检查轴套并更换密封组件。", ["mechanical seal kit", "spill containment kit", "gasket set"], ["pump maintenance", "hazardous material response", "LOTO authorization"], 110, 1800, "泵维修与 EHS 联合组", "立即降载并准备安全隔离", "仅在泄漏量低于 EHS 阈值且具备围堵措施时短时运行。"),
    },
    {
        "id": "fan_blade_fouling",
        "name": "风机叶片积灰",
        "category": "泵风机与流体设备",
        "description": "一倍频升高、风量下降与视觉积灰提示叶片污染。",
        "modalities": ["振动", "风量", "视觉"],
        "severity": "medium",
        "asset_types": ["风机"],
        "summary": "排风机一倍频振动升高，风量下降且叶片表面存在不均匀积灰。",
        "telemetry": _telemetry(2.16, 3.2, 3.0, 62.8, 1450, 69, 68.4, 4.2, 8.2),
        "vision": {"anomaly_score": 0.86, "class_name": "blade_fouling", "confidence": 0.89},
        "operator_note": "最近喷涂工艺粉尘负荷增加。",
        "fault_mode": "风机叶片不均匀积灰",
        "rationale": "不平衡型振动、风量下降和直接视觉积灰证据一致。",
        "alternatives": ["叶片变形", "转子不平衡"],
        "maintenance": _maintenance("停机清洁叶轮并复核平衡", "清洁叶片、检查腐蚀和变形，并复测振动与风量。", ["cleaning consumables", "balancing weight kit"], ["fan maintenance", "confined-space awareness", "LOTO authorization"], 60, 420, "暖通与机械可靠性组"),
    },
    {
        "id": "motor_bearing_overheat",
        "name": "电机轴承过热",
        "category": "电机与电气",
        "description": "轴承座温升和振动共同增大，可能涉及润滑、负载或电气应力。",
        "modalities": ["温度", "振动", "电流"],
        "severity": "high",
        "asset_types": ["电机"],
        "summary": "电机驱动端轴承温度持续上升，振动与电流同时偏离基线。",
        "telemetry": _telemetry(2.35, 4.9, 4.1, 96.0, 2980, 91, 72.3, 7.8, 18.7),
        "vision": {"anomaly_score": 0.35, "class_name": "thermal_hotspot", "confidence": 0.72},
        "operator_note": "环境温度正常，负载较前班次略有升高。",
        "fault_mode": "电机轴承过热",
        "rationale": "轴承局部温升与振动、电流异常共同说明摩擦或负载相关劣化。",
        "alternatives": ["润滑不足", "电机过载"],
        "maintenance": _maintenance("停机检查轴承、润滑和负载", "检查轴承游隙、润滑状态、电机负载与冷却通道，按结果维修。", ["motor bearing set", "approved grease cartridge"], ["motor maintenance", "thermography", "electrical isolation"], 90, 980, "电气可靠性 B 组"),
    },
    {
        "id": "electrical_unbalance",
        "name": "三相电流不平衡",
        "category": "电机与电气",
        "description": "负序电流、温升和转矩脉动提示供电或绕组不平衡。",
        "modalities": ["三相电流", "温度", "振动"],
        "severity": "high",
        "asset_types": ["电机"],
        "summary": "三相电流偏差超过阈值，电机温升和二倍电源频率振动增加。",
        "telemetry": _telemetry(1.94, 3.7, 3.2, 88.6, 2985, 86, 69.8, 8.9, 19.4),
        "vision": {"anomaly_score": 0.22, "class_name": None, "confidence": 0.54},
        "operator_note": "同一配电支路近期新增了大功率负载。",
        "fault_mode": "电源或绕组三相不平衡",
        "rationale": "电流偏差与二倍电源频率振动及温升组合符合电气不平衡。",
        "alternatives": ["电机过载", "接线端子接触不良"],
        "maintenance": _maintenance("安排电气隔离并检查供电与绕组", "测量三相电压、电流和绝缘，检查端子、接触器与绕组。", ["electrical test kit", "terminal hardware"], ["electrical maintenance", "electrical isolation", "motor diagnostics"], 75, 760, "电气可靠性 B 组"),
    },
    {
        "id": "energy_drift",
        "name": "设备能效漂移",
        "category": "能源与环境",
        "description": "生产负载不变时，能耗持续高于资产基线。",
        "modalities": ["电能", "产量", "负载", "振动"],
        "severity": "medium",
        "asset_types": ["通用设备"],
        "summary": "生产负载未增加，但设备能耗明显上升。",
        "telemetry": _telemetry(1.72, 4.2, 3.5, 72.8, 2880, 68, 68.0, 5.3, 16.4),
        "vision": {"anomaly_score": 0.28, "class_name": "belt_slip_suspected", "confidence": 0.61},
        "operator_note": "生产配方没有变更记录。",
        "fault_mode": "机械效率下降导致能效漂移",
        "rationale": "能耗增加与产量负载脱钩，且存在轻度机械异常证据。",
        "alternatives": ["计量偏差", "工艺设定改变"],
        "maintenance": _maintenance("执行能效诊断和机械检查", "核对电能计量，检查摩擦、皮带、过滤器和负载路径，建立维修前后能效对比。", ["portable power analyzer", "inspection consumables"], ["energy analysis", "mechanical inspection", "electrical safety"], 65, 650, "能源与可靠性联合组"),
    },
    {
        "id": "cooling_efficiency_loss",
        "name": "冷却效率下降",
        "category": "能源与环境",
        "description": "冷却功率增加但温度下降能力减弱，提示换热器污染或流量不足。",
        "modalities": ["温度", "流量", "能耗"],
        "severity": "medium",
        "asset_types": ["冷却系统", "换热器"],
        "summary": "冷却系统功率增加，但回水温差和降温能力持续下降。",
        "telemetry": _telemetry(1.35, 3.2, 2.8, 83.2, 1460, 78, 66.5, 5.8, 17.6),
        "vision": {"anomaly_score": 0.65, "class_name": "heat_exchanger_fouling", "confidence": 0.77},
        "operator_note": "过滤器压差接近维护阈值。",
        "fault_mode": "冷却系统换热效率下降",
        "rationale": "能耗增加与温差能力下降，结合过滤或换热污染证据，支持冷却效率损失。",
        "alternatives": ["传感器偏差", "冷媒不足"],
        "maintenance": _maintenance("清洁过滤与换热表面", "检查流量、过滤器压差、换热器污染和冷媒状态，维修后复核 COP。", ["filter element", "cleaning chemicals"], ["HVAC maintenance", "energy analysis", "LOTO authorization"], 95, 920, "公用工程与能源组"),
    },
    {
        "id": "compressed_air_leak",
        "name": "压缩空气泄漏",
        "category": "能源与环境",
        "description": "空压机负载率升高但末端用气量不变，超声信号定位泄漏。",
        "modalities": ["流量", "压力", "超声", "能耗"],
        "severity": "medium",
        "asset_types": ["空压机", "管网"],
        "summary": "空压机加载时间增加，管网压力下降且检测到持续超声泄漏信号。",
        "telemetry": _telemetry(1.12, 3.0, 2.7, 68.3, 2980, 74, 85.1, 9.2, 22.8),
        "vision": {"anomaly_score": 0.72, "class_name": "air_leak", "confidence": 0.82},
        "operator_note": "夜间停产时基线流量仍明显偏高。",
        "fault_mode": "压缩空气管网泄漏",
        "rationale": "停产基线流量、压力下降与超声定位共同支持泄漏。",
        "alternatives": ["压力设定过高", "流量计偏差"],
        "maintenance": _maintenance("隔离泄漏点并修复管路", "按区域隔离定位，修复接头、软管或阀门并复核夜间基线流量。", ["pneumatic fitting kit", "sealant", "hose set"], ["compressed air maintenance", "ultrasound inspection", "LOTO authorization"], 45, 260, "公用工程维护组"),
    },
    {
        "id": "sensor_conflict",
        "name": "跨模态证据冲突",
        "category": "数据质量与治理",
        "description": "振动提示冲击，但视觉与温度没有支持，系统应拒绝过度自信。",
        "modalities": ["振动", "视觉", "质量门控"],
        "severity": "medium",
        "asset_types": ["通用设备"],
        "summary": "传感器证据存在冲突：振动显示冲击，视觉结果正常。",
        "telemetry": _telemetry(3.6, 8.1, 5.9, 58.2, 2990, 61, 64.0, 4.2, 12.4, 0.62),
        "vision": {"anomaly_score": 0.18, "class_name": None, "confidence": 0.82},
        "operator_note": "加速度传感器今天上午重新安装过。",
        "fault_mode": "证据冲突，故障模式尚未解析",
        "rationale": "振动冲击与视觉正常相互矛盾，必须补采而不能直接下结论。",
        "alternatives": ["传感器安装问题", "早期局部缺陷"],
        "force_reacquire": True,
        "maintenance": _maintenance("验证传感器安装并重新采集", "复核安装方向、扭矩、采样率和时间同步，采集第二角度图像后重新诊断。", ["sensor mounting kit"], ["condition monitoring", "sensor installation"], 15, 60, "状态监测组", "维持安全状态并等待补采", "不执行维修动作，只保持安全运行边界。"),
    },
    {
        "id": "sensor_mounting_error",
        "name": "传感器安装异常",
        "category": "数据质量与治理",
        "description": "直流偏置、低有效位数和方向异常提示采集链路问题。",
        "modalities": ["信号质量", "安装记录"],
        "severity": "low",
        "asset_types": ["通用设备"],
        "summary": "加速度信号出现明显基线偏置和安装方向不一致。",
        "telemetry": _telemetry(3.1, 7.7, 5.4, 55.0, 1800, 55, 61.0, 4.0, 11.9, 0.48),
        "vision": {"anomaly_score": 0.12, "class_name": "sensor_mount_loose", "confidence": 0.72},
        "operator_note": "传感器底座由临时磁座改为胶粘安装。",
        "fault_mode": "传感器安装或量程配置异常",
        "rationale": "低质量评分与安装记录变化足以否定自动故障结论。",
        "alternatives": ["线缆接触不良", "实际冲击故障"],
        "force_reacquire": True,
        "maintenance": _maintenance("恢复标准安装并校验采集链路", "按标准位置和扭矩安装传感器，核对量程、单位和轴向映射。", ["sensor mounting stud", "calibration reference"], ["sensor installation", "data acquisition validation"], 20, 80, "状态监测组"),
    },
    {
        "id": "packet_loss",
        "name": "边缘数据丢包",
        "category": "数据质量与治理",
        "description": "时间戳间隔不连续和窗口缺失影响实时诊断可信度。",
        "modalities": ["网络", "时间戳", "边缘缓存"],
        "severity": "medium",
        "asset_types": ["边缘节点"],
        "summary": "边缘节点上报数据帧出现连续丢包和时间戳跳变。",
        "telemetry": _telemetry(1.9, 4.1, 3.4, 63.0, 1800, 65, 65.0, 4.1, 12.0, 0.58),
        "vision": {"anomaly_score": 0.11, "class_name": None, "confidence": 0.5},
        "operator_note": "无线网络切换后发生数据间断。",
        "fault_mode": "边缘数据链路丢包或时钟异常",
        "rationale": "数据完整性不足，任何设备故障判断都必须降级。",
        "alternatives": ["边缘缓存写入失败", "网关时钟漂移"],
        "force_reacquire": True,
        "maintenance": _maintenance("恢复网络与边缘缓存一致性", "检查 MQTT/HTTP 链路、时钟同步和本地队列，补传后再恢复自动诊断。", ["network diagnostic kit"], ["OT network maintenance", "edge runtime operations"], 25, 120, "OT 网络与边缘平台组"),
    },
    {
        "id": "supply_constraint",
        "name": "备件供应受限",
        "category": "生产与韧性",
        "description": "设备劣化与备件交期延长同时发生，需要联合评估替代件和生产缓冲。",
        "modalities": ["设备健康", "库存", "供应商", "排产"],
        "severity": "high",
        "asset_types": ["关键资产"],
        "summary": "检测到轴承劣化，同时常规备件供应路径受限。",
        "telemetry": _telemetry(2.65, 6.7, 4.9, 74.4, 2960, 77, 72.0, 4.7, 13.6, 0.95),
        "vision": {"anomaly_score": 0.72, "class_name": "spall", "confidence": 0.76},
        "operator_note": "物流中断后，供应商交期延长。",
        "fault_mode": "关键轴承劣化并伴随备件供应风险",
        "rationale": "设备劣化证据明确，但执行方案必须受可用库存与供应交期约束。",
        "alternatives": ["使用认证替代件", "切换备用设备"],
        "maintenance": _maintenance("锁定可用备件并安排最近窗口更换", "核对替代件兼容性、库存和供应交期，必要时切换备用设备或限制负载。", ["compatible certified bearing", "approved grease cartridge"], ["mechanical maintenance", "inventory authorization", "production planning"], 70, 680, "可靠性、采购与生产联合组"),
    },
    {
        "id": "technician_shortage",
        "name": "关键技能人员不足",
        "category": "生产与韧性",
        "description": "故障可维修但当前班次缺少必要资质人员，需要安全排班或远程支持。",
        "modalities": ["人员技能", "排班", "设备风险"],
        "severity": "high",
        "asset_types": ["关键资产"],
        "summary": "设备需要高风险维修，但当前班次缺少具备隔离和精密对中资质的人员。",
        "telemetry": _telemetry(2.48, 5.9, 4.6, 75.1, 1780, 80, 71.8, 5.2, 14.6, 0.96),
        "vision": {"anomaly_score": 0.58, "class_name": "coupling_offset", "confidence": 0.68},
        "operator_note": "夜班仅有一名机械维修人员，且无精密对中授权。",
        "fault_mode": "设备劣化与关键技能可用性冲突",
        "rationale": "维修技术路径明确，但人员资质不足构成不可绕过的安全约束。",
        "alternatives": ["远程专家指导", "延迟至合格班组到场"],
        "maintenance": _maintenance("等待合格人员并准备受控停机", "冻结高风险工具调用，协调具备 LOTO 和精密对中资质的人员到场。", ["laser alignment kit"], ["precision alignment", "LOTO authorization", "maintenance supervision"], 90, 880, "机械可靠性与值班管理组", "降载监控至合格人员到场", "仅在硬停机阈值和主管授权下维持受限运行。"),
    },
    {
        "id": "production_overload",
        "name": "生产负载异常",
        "category": "生产与韧性",
        "description": "设备负载持续超过工艺基线，寿命损耗和能源风险同步增加。",
        "modalities": ["负载", "排产", "电流", "能耗"],
        "severity": "high",
        "asset_types": ["生产设备"],
        "summary": "设备连续高负载运行，电流、温度和能耗均超过计划基线。",
        "telemetry": _telemetry(2.12, 4.1, 3.6, 89.4, 3000, 118, 72.0, 9.6, 21.8, 0.98),
        "vision": {"anomaly_score": 0.25, "class_name": None, "confidence": 0.51},
        "operator_note": "临时插单导致设备连续超计划负载运行。",
        "fault_mode": "生产负载超限引起的加速劣化",
        "rationale": "负载、电流、温度和能耗同时超限，属于生产约束触发的设备风险。",
        "alternatives": ["冷却能力不足", "电机效率下降"],
        "maintenance": _maintenance("重排生产并恢复允许负载", "拆分批次、切换备用资源并安排检查，避免继续累积寿命损耗。", [], ["production planning", "reliability engineering", "authorized supervisor"], 25, 120, "生产计划与可靠性联合组"),
    },
]


_SCENARIO_BY_ID = {item["id"]: item for item in SCENARIOS}


def list_scenarios() -> list[dict[str, Any]]:
    return [
        {
            key: deepcopy(value)
            for key, value in item.items()
            if key not in {"telemetry", "vision", "operator_note", "rationale", "alternatives", "maintenance", "force_reacquire"}
        }
        | {
            "maintenance_summary": item["maintenance"]["title"],
            "demo_only": True,
        }
        for item in SCENARIOS
    ]


def get_scenario(scenario_id: str) -> dict[str, Any]:
    try:
        return deepcopy(_SCENARIO_BY_ID[scenario_id])
    except KeyError as exc:
        valid = ", ".join(sorted(_SCENARIO_BY_ID))
        raise ValueError(f"Unknown demo scenario: {scenario_id}. Valid values: {valid}") from exc
