from __future__ import annotations

import codecs
import csv
from dataclasses import asdict, dataclass


MIB = 1024 * 1024


@dataclass(frozen=True, slots=True)
class CsvPolicy:
    name: str
    max_bytes: int
    max_rows: int
    max_columns: int
    max_cell_characters: int
    encodings: tuple[str, ...]
    delimiters: tuple[str, ...]
    header: str
    notes: str

    def public(self) -> dict[str, object]:
        payload = asdict(self)
        payload["max_size_mb"] = self.max_bytes // MIB
        return payload


ANALYSIS_CSV_POLICY = CsvPolicy(
    name="historical-analysis-upload",
    max_bytes=128 * MIB,
    max_rows=1_000_000,
    max_columns=256,
    max_cell_characters=1 * MIB,
    encodings=("utf-8-sig", "gb18030", "utf-16"),
    delimiters=(",", ";", "\t", "|"),
    header="optional",
    notes="At least 64 finite numeric values are required in the selected signal column.",
)

SUBMISSION_CSV_POLICY = CsvPolicy(
    name="openeval-submission",
    max_bytes=10 * MIB,
    max_rows=100_000,
    max_columns=16,
    max_cell_characters=16_384,
    encodings=("utf-8-sig", "gb18030"),
    delimiters=(",",),
    header="required: sample_id,predicted_label,confidence",
    notes="Exactly one prediction is required for every test sample.",
)

XJTU_CSV_POLICY = CsvPolicy(
    name="xjtu-sy-recording",
    max_bytes=64 * MIB,
    max_rows=1_000_000,
    max_columns=64,
    max_cell_characters=1 * MIB,
    encodings=("utf-8-sig",),
    delimiters=(",",),
    header="one header row required",
    notes="The first two numeric columns are horizontal and vertical vibration.",
)

OPEN_EVAL_INDEX_POLICY = CsvPolicy(
    name="openeval-generated-index",
    max_bytes=32 * MIB,
    max_rows=100_000,
    max_columns=32,
    max_cell_characters=16_384,
    encodings=("utf-8",),
    delimiters=(",",),
    header="required",
    notes="Generated by ForgeGuard; limits are checked before writing.",
)


def ensure_csv_size(size: int, policy: CsvPolicy) -> None:
    if size > policy.max_bytes:
        raise ValueError(
            f"CSV file exceeds the {policy.max_bytes // MIB} MB limit for {policy.name}"
        )


def decode_csv_bytes(content: bytes, policy: CsvPolicy) -> tuple[str, str]:
    ensure_csv_size(len(content), policy)
    if content.startswith((codecs.BOM_UTF16_LE, codecs.BOM_UTF16_BE)):
        try:
            return content.decode("utf-16"), "utf-16"
        except UnicodeDecodeError as exc:
            raise ValueError("CSV has an invalid UTF-16 byte sequence") from exc
    for encoding in policy.encodings:
        if encoding == "utf-16":
            continue
        try:
            return content.decode(encoding), encoding
        except UnicodeDecodeError:
            continue
    readable = ", ".join(policy.encodings)
    raise ValueError(f"CSV encoding is not supported; use {readable}")


def sniff_csv_dialect(text: str, policy: CsvPolicy) -> csv.Dialect:
    try:
        return csv.Sniffer().sniff(text[:16_384], delimiters="".join(policy.delimiters))
    except csv.Error:
        class DefaultDialect(csv.excel):
            delimiter = policy.delimiters[0]

        return DefaultDialect()


def csv_policy_catalog() -> dict[str, dict[str, object]]:
    return {
        policy.name: policy.public()
        for policy in (
            ANALYSIS_CSV_POLICY,
            SUBMISSION_CSV_POLICY,
            XJTU_CSV_POLICY,
            OPEN_EVAL_INDEX_POLICY,
        )
    }
